;;; rose-pine-moon-theme.el --- Rosé Pine Moon -*- lexical-binding: t -*-

(deftheme rose-pine-moon "Rosé Pine Moon variant.")

(let ((base       "#232136")
      (surface    "#2a273f")
      (overlay    "#393552")
      (muted      "#6e6a86")
      (subtle     "#908caa")
      (text       "#e0def4")
      (love       "#eb6f92")
      (gold       "#f6c177")
      (rose       "#ea9a97")
      (pine       "#3e8fb0")
      (foam       "#9ccfd8")
      (iris       "#c4a7e7")
      (hl-low     "#2a283e")
      (hl-med     "#44415a")
      (hl-high    "#56526e"))

  (custom-theme-set-faces
   'rose-pine-moon

   `(default                    ((t :background ,base    :foreground ,text)))
   `(fringe                     ((t :background ,base    :foreground ,muted)))
   `(vertical-border            ((t :foreground ,overlay)))
   `(border                     ((t :foreground ,overlay)))
   `(cursor                     ((t :background ,rose)))
   `(highlight                  ((t :background ,hl-med)))
   `(region                     ((t :background ,hl-med  :extend t)))
   `(secondary-selection        ((t :background ,hl-low  :extend t)))
   `(hl-line                    ((t :background ,hl-low  :extend t)))
   `(match                      ((t :foreground ,rose    :weight bold)))
   `(shadow                     ((t :foreground ,muted)))
   `(minibuffer-prompt          ((t :foreground ,iris    :weight bold)))
   `(error                      ((t :foreground ,love    :weight bold)))
   `(warning                    ((t :foreground ,gold    :weight bold)))
   `(success                    ((t :foreground ,foam    :weight bold)))
   `(escape-glyph               ((t :foreground ,rose)))
   `(trailing-whitespace        ((t :background ,love)))

   `(line-number                ((t :background ,base    :foreground ,muted)))
   `(line-number-current-line   ((t :background ,base    :foreground ,subtle  :weight bold)))

   `(mode-line                  ((t :background ,overlay :foreground ,subtle)))
   `(mode-line-inactive         ((t :background ,surface :foreground ,muted)))
   `(mode-line-buffer-id        ((t :foreground ,text    :weight bold)))
   `(mode-line-emphasis         ((t :foreground ,iris    :weight bold)))
   `(mode-line-highlight        ((t :foreground ,rose)))

   `(link                       ((t :foreground ,iris    :underline t)))
   `(link-visited               ((t :foreground ,muted   :underline t)))
   `(button                     ((t :foreground ,iris    :underline t)))

   `(isearch                    ((t :background ,rose    :foreground ,base    :weight bold)))
   `(isearch-fail               ((t :background ,love    :foreground ,base)))
   `(lazy-highlight             ((t :background ,hl-med  :foreground ,subtle)))
   `(query-replace              ((t :background ,gold    :foreground ,base)))

   `(font-lock-keyword-face           ((t :foreground ,pine)))
   `(font-lock-function-name-face     ((t :foreground ,rose)))
   `(font-lock-type-face              ((t :foreground ,foam)))
   `(font-lock-builtin-face           ((t :foreground ,love)))
   `(font-lock-constant-face          ((t :foreground ,iris)))
   `(font-lock-string-face            ((t :foreground ,gold)))
   `(font-lock-variable-name-face     ((t :foreground ,foam)))
   `(font-lock-comment-face           ((t :foreground ,muted  :slant italic)))
   `(font-lock-comment-delimiter-face ((t :foreground ,muted  :slant italic)))
   `(font-lock-doc-face               ((t :foreground ,muted  :slant italic)))
   `(font-lock-doc-markup-face        ((t :foreground ,subtle)))
   `(font-lock-preprocessor-face      ((t :foreground ,iris)))
   `(font-lock-negation-char-face     ((t :foreground ,love)))
   `(font-lock-warning-face           ((t :foreground ,love   :weight bold)))
   `(font-lock-number-face            ((t :foreground ,iris)))
   `(font-lock-operator-face          ((t :foreground ,subtle)))
   `(font-lock-punctuation-face       ((t :foreground ,subtle)))
   `(font-lock-bracket-face           ((t :foreground ,subtle)))
   `(font-lock-delimiter-face         ((t :foreground ,subtle)))
   `(font-lock-regexp-grouping-backslash ((t :foreground ,pine)))
   `(font-lock-regexp-grouping-construct ((t :foreground ,iris)))

   `(completions-annotations          ((t :foreground ,muted)))
   `(completions-common-part          ((t :foreground ,iris   :weight bold)))
   `(completions-first-difference     ((t :foreground ,love)))

   `(dired-directory            ((t :foreground ,foam    :weight bold)))
   `(dired-flagged              ((t :foreground ,love)))
   `(dired-header               ((t :foreground ,pine    :weight bold)))
   `(dired-mark                 ((t :foreground ,gold)))
   `(dired-symlink              ((t :foreground ,rose)))

   `(whitespace-tab             ((t :background ,base    :foreground ,hl-med)))
   `(whitespace-newline         ((t :foreground ,hl-med)))
   `(whitespace-trailing        ((t :background ,love)))
   `(whitespace-space           ((t :foreground ,hl-med)))

   `(org-block                  ((t :background ,surface :extend t)))
   `(org-block-begin-line       ((t :background ,surface :foreground ,muted   :slant italic :extend t)))
   `(org-block-end-line         ((t :background ,surface :foreground ,muted   :slant italic :extend t)))
   `(org-code                   ((t :foreground ,gold)))
   `(org-verbatim               ((t :foreground ,gold)))
   `(org-date                   ((t :foreground ,iris)))
   `(org-document-title         ((t :foreground ,text    :weight bold)))
   `(org-done                   ((t :foreground ,muted)))
   `(org-todo                   ((t :foreground ,love    :weight bold)))
   `(org-level-1                ((t :foreground ,rose    :weight bold)))
   `(org-level-2                ((t :foreground ,foam    :weight bold)))
   `(org-level-3                ((t :foreground ,iris    :weight bold)))
   `(org-level-4                ((t :foreground ,gold    :weight bold)))
   `(org-level-5                ((t :foreground ,pine    :weight bold)))
   `(org-level-6                ((t :foreground ,love    :weight bold)))
   `(org-link                   ((t :foreground ,iris    :underline t)))
   `(org-meta-line              ((t :foreground ,muted)))
   `(org-table                  ((t :foreground ,subtle)))
   `(org-tag                    ((t :foreground ,muted   :weight bold)))
   `(org-warning                ((t :foreground ,gold    :weight bold)))

   `(vertico-current            ((t :background ,hl-med  :extend t)))
   `(marginalia-documentation   ((t :foreground ,muted   :slant italic)))
   `(orderless-match-face-0     ((t :foreground ,iris    :weight bold)))
   `(orderless-match-face-1     ((t :foreground ,rose    :weight bold)))
   `(orderless-match-face-2     ((t :foreground ,foam    :weight bold)))
   `(orderless-match-face-3     ((t :foreground ,gold    :weight bold)))

   `(corfu-default              ((t :background ,overlay)))
   `(corfu-current              ((t :background ,hl-med)))
   `(corfu-bar                  ((t :background ,muted)))
   `(corfu-border               ((t :background ,hl-high)))
   `(corfu-annotations          ((t :foreground ,muted)))

   `(eglot-highlight-symbol-face          ((t :background ,hl-med)))
   `(eglot-diagnostic-tag-unnecessary-face ((t :foreground ,muted)))

   `(flymake-error              ((t :underline (:style wave :color ,love))))
   `(flymake-warning            ((t :underline (:style wave :color ,gold))))
   `(flymake-note               ((t :underline (:style wave :color ,foam))))

   `(magit-branch-local                   ((t :foreground ,foam)))
   `(magit-branch-remote                  ((t :foreground ,pine)))
   `(magit-diff-added                     ((t :background "#1e3530" :foreground ,foam    :extend t)))
   `(magit-diff-added-highlight           ((t :background "#22403a" :foreground ,foam    :extend t)))
   `(magit-diff-removed                   ((t :background "#361e2a" :foreground ,love    :extend t)))
   `(magit-diff-removed-highlight         ((t :background "#3f2232" :foreground ,love    :extend t)))
   `(magit-diff-context                   ((t :foreground ,muted    :extend t)))
   `(magit-diff-context-highlight         ((t :background ,surface  :foreground ,subtle  :extend t)))
   `(magit-diff-hunk-heading              ((t :background ,overlay  :foreground ,subtle)))
   `(magit-diff-hunk-heading-highlight    ((t :background ,overlay  :foreground ,text    :weight bold)))
   `(magit-filename                       ((t :foreground ,rose)))
   `(magit-hash                           ((t :foreground ,muted)))
   `(magit-log-author                     ((t :foreground ,gold)))
   `(magit-log-date                       ((t :foreground ,subtle)))
   `(magit-process-ng                     ((t :foreground ,love     :weight bold)))
   `(magit-process-ok                     ((t :foreground ,foam     :weight bold)))
   `(magit-section-heading                ((t :foreground ,gold     :weight bold)))
   `(magit-section-highlight              ((t :background ,surface  :extend t)))
   `(magit-tag                            ((t :foreground ,gold)))

   `(diff-hl-insert             ((t :foreground ,foam    :background ,foam)))
   `(diff-hl-delete             ((t :foreground ,love    :background ,love)))
   `(diff-hl-change             ((t :foreground ,gold    :background ,gold)))

   `(tab-bar                    ((t :background ,base    :foreground ,subtle)))
   `(tab-bar-tab                ((t :background ,overlay :foreground ,text    :weight bold)))
   `(tab-bar-tab-inactive       ((t :background ,base    :foreground ,muted)))))

(provide-theme 'rose-pine-moon)
;;; rose-pine-moon-theme.el ends here
